/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package habitabbilidad;

import Mundo.Habitacion;
import algoritmo.algoritmo;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author TOSHIBA
 */
public class EDIFICIO extends javax.swing.JFrame {

    /**
     * Creates new form EDIFICIO
     */
    String[][] habitabilidad;
    String costoTotalActual ="";
    Habitacion habitacion101;
    Habitacion habitacion102;
    Habitacion habitacion103;
    Habitacion habitacion104;
    Habitacion habitacion105;
    Habitacion habitacion106;
    Habitacion habitacion201;
    Habitacion habitacion202;
    Habitacion habitacion203;
    Habitacion habitacion204;
    Habitacion habitacion205;
    Habitacion habitacion206;
    Habitacion habitacion301;
    Habitacion habitacion302;
    Habitacion habitacion303;
    Habitacion habitacion304;
    Habitacion habitacion305;
    Habitacion habitacion306;
    
    public EDIFICIO() {
        initComponents();
        llenarHabitaciones();
    }
    public  void llenarHabitaciones(){
        habitacion101 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion102 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion103 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion104 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion105 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion106 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion201 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion202 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion203 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion204 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion205 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion206 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion301 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion302 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido"); 
        habitacion303 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion304 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion305 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
        habitacion306 = new Habitacion("carton", "pvc", "pvc", "regillas",5,2,3,1,11,"desconosido","desconosido");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edi305 = new javax.swing.JButton();
        edi304 = new javax.swing.JButton();
        edi301 = new javax.swing.JButton();
        edi303 = new javax.swing.JButton();
        edi302 = new javax.swing.JButton();
        edi306 = new javax.swing.JButton();
        edi205 = new javax.swing.JButton();
        edi204 = new javax.swing.JButton();
        edi203 = new javax.swing.JButton();
        edi201 = new javax.swing.JButton();
        edi202 = new javax.swing.JButton();
        edi106 = new javax.swing.JButton();
        edi105 = new javax.swing.JButton();
        edi104 = new javax.swing.JButton();
        edi102 = new javax.swing.JButton();
        edi101 = new javax.swing.JButton();
        edi206 = new javax.swing.JButton();
        edi103 = new javax.swing.JButton();
        numeroHabitacion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pared = new javax.swing.JComboBox<>();
        techo = new javax.swing.JComboBox<>();
        suelo = new javax.swing.JComboBox<>();
        ventilacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        costoHabitacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CALCULAR = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        temperatura = new javax.swing.JLabel();
        olor = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        costoEdificio = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        edi305.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi305.setForeground(new java.awt.Color(102, 102, 102));
        edi305.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi305.setText("305");
        edi305.setBorderPainted(false);
        edi305.setContentAreaFilled(false);
        edi305.setDefaultCapable(false);
        edi305.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi305.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi305ActionPerformed(evt);
            }
        });
        getContentPane().add(edi305);
        edi305.setBounds(70, 120, 74, 71);

        edi304.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi304.setForeground(new java.awt.Color(102, 102, 102));
        edi304.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi304.setText("304");
        edi304.setBorderPainted(false);
        edi304.setContentAreaFilled(false);
        edi304.setDefaultCapable(false);
        edi304.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi304.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi304ActionPerformed(evt);
            }
        });
        getContentPane().add(edi304);
        edi304.setBounds(260, 50, 74, 71);

        edi301.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi301.setForeground(new java.awt.Color(102, 102, 102));
        edi301.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi301.setText("301");
        edi301.setBorderPainted(false);
        edi301.setContentAreaFilled(false);
        edi301.setDefaultCapable(false);
        edi301.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi301.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi301ActionPerformed(evt);
            }
        });
        getContentPane().add(edi301);
        edi301.setBounds(250, 320, 74, 71);

        edi303.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi303.setForeground(new java.awt.Color(102, 102, 102));
        edi303.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi303.setText("303");
        edi303.setBorderPainted(false);
        edi303.setContentAreaFilled(false);
        edi303.setDefaultCapable(false);
        edi303.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi303ActionPerformed(evt);
            }
        });
        getContentPane().add(edi303);
        edi303.setBounds(450, 120, 74, 71);

        edi302.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi302.setForeground(new java.awt.Color(102, 102, 102));
        edi302.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi302.setText("302");
        edi302.setBorderPainted(false);
        edi302.setContentAreaFilled(false);
        edi302.setDefaultCapable(false);
        edi302.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi302.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi302ActionPerformed(evt);
            }
        });
        getContentPane().add(edi302);
        edi302.setBounds(450, 260, 74, 71);

        edi306.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi306.setForeground(new java.awt.Color(102, 102, 102));
        edi306.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi306.setText("306");
        edi306.setBorderPainted(false);
        edi306.setContentAreaFilled(false);
        edi306.setDefaultCapable(false);
        edi306.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi306.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi306ActionPerformed(evt);
            }
        });
        getContentPane().add(edi306);
        edi306.setBounds(70, 260, 74, 71);

        edi205.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi205.setForeground(new java.awt.Color(102, 102, 102));
        edi205.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi205.setText("205");
        edi205.setBorderPainted(false);
        edi205.setContentAreaFilled(false);
        edi205.setDefaultCapable(false);
        edi205.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi205.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi205ActionPerformed(evt);
            }
        });
        getContentPane().add(edi205);
        edi205.setBounds(160, 380, 74, 71);

        edi204.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi204.setForeground(new java.awt.Color(102, 102, 102));
        edi204.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi204.setText("204");
        edi204.setBorderPainted(false);
        edi204.setContentAreaFilled(false);
        edi204.setDefaultCapable(false);
        edi204.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi204ActionPerformed(evt);
            }
        });
        getContentPane().add(edi204);
        edi204.setBounds(340, 310, 74, 71);

        edi203.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi203.setForeground(new java.awt.Color(102, 102, 102));
        edi203.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi203.setText("203");
        edi203.setBorderPainted(false);
        edi203.setContentAreaFilled(false);
        edi203.setDefaultCapable(false);
        edi203.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi203ActionPerformed(evt);
            }
        });
        getContentPane().add(edi203);
        edi203.setBounds(530, 380, 74, 71);

        edi201.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi201.setForeground(new java.awt.Color(102, 102, 102));
        edi201.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi201.setText("201");
        edi201.setBorderPainted(false);
        edi201.setContentAreaFilled(false);
        edi201.setDefaultCapable(false);
        edi201.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi201ActionPerformed(evt);
            }
        });
        getContentPane().add(edi201);
        edi201.setBounds(340, 580, 74, 71);

        edi202.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi202.setForeground(new java.awt.Color(102, 102, 102));
        edi202.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi202.setText("202");
        edi202.setBorderPainted(false);
        edi202.setContentAreaFilled(false);
        edi202.setDefaultCapable(false);
        edi202.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi202ActionPerformed(evt);
            }
        });
        getContentPane().add(edi202);
        edi202.setBounds(530, 510, 74, 71);

        edi106.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi106.setForeground(new java.awt.Color(102, 102, 102));
        edi106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi106.setText("106");
        edi106.setBorderPainted(false);
        edi106.setContentAreaFilled(false);
        edi106.setDefaultCapable(false);
        edi106.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi106ActionPerformed(evt);
            }
        });
        getContentPane().add(edi106);
        edi106.setBounds(210, 690, 74, 71);

        edi105.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi105.setForeground(new java.awt.Color(102, 102, 102));
        edi105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi105.setText("105");
        edi105.setBorderPainted(false);
        edi105.setContentAreaFilled(false);
        edi105.setDefaultCapable(false);
        edi105.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi105ActionPerformed(evt);
            }
        });
        getContentPane().add(edi105);
        edi105.setBounds(210, 560, 74, 71);

        edi104.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi104.setForeground(new java.awt.Color(102, 102, 102));
        edi104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi104.setText("104");
        edi104.setBorderPainted(false);
        edi104.setContentAreaFilled(false);
        edi104.setDefaultCapable(false);
        edi104.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi104ActionPerformed(evt);
            }
        });
        getContentPane().add(edi104);
        edi104.setBounds(400, 490, 74, 71);

        edi102.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi102.setForeground(new java.awt.Color(102, 102, 102));
        edi102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi102.setText("102");
        edi102.setBorderPainted(false);
        edi102.setContentAreaFilled(false);
        edi102.setDefaultCapable(false);
        edi102.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi102ActionPerformed(evt);
            }
        });
        getContentPane().add(edi102);
        edi102.setBounds(590, 690, 74, 71);

        edi101.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi101.setForeground(new java.awt.Color(102, 102, 102));
        edi101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi101.setText("101");
        edi101.setBorderPainted(false);
        edi101.setContentAreaFilled(false);
        edi101.setDefaultCapable(false);
        edi101.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi101ActionPerformed(evt);
            }
        });
        getContentPane().add(edi101);
        edi101.setBounds(400, 750, 74, 71);

        edi206.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi206.setForeground(new java.awt.Color(102, 102, 102));
        edi206.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi206.setText("206");
        edi206.setBorderPainted(false);
        edi206.setContentAreaFilled(false);
        edi206.setDefaultCapable(false);
        edi206.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi206.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi206ActionPerformed(evt);
            }
        });
        getContentPane().add(edi206);
        edi206.setBounds(150, 510, 74, 71);

        edi103.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        edi103.setForeground(new java.awt.Color(102, 102, 102));
        edi103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton gris.PNG"))); // NOI18N
        edi103.setText("103");
        edi103.setBorderPainted(false);
        edi103.setContentAreaFilled(false);
        edi103.setDefaultCapable(false);
        edi103.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edi103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edi103ActionPerformed(evt);
            }
        });
        getContentPane().add(edi103);
        edi103.setBounds(590, 560, 74, 71);

        numeroHabitacion.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        numeroHabitacion.setText("101");
        getContentPane().add(numeroHabitacion);
        numeroHabitacion.setBounds(810, 130, 50, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("HABITACION ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(770, 100, 130, 50);

        pared.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "carton", "cemento", "sintetico" }));
        getContentPane().add(pared);
        pared.setBounds(670, 210, 90, 22);

        techo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pvc", "cemento", "sintetico" }));
        getContentPane().add(techo);
        techo.setBounds(790, 210, 90, 22);

        suelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pvc", "cemento", "sintetico" }));
        getContentPane().add(suelo);
        suelo.setBounds(910, 210, 90, 22);

        ventilacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "regillas", "ducto", "aireAcondicionado" }));
        getContentPane().add(ventilacion);
        ventilacion.setBounds(780, 280, 110, 22);

        jLabel4.setText("PAREDES");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(680, 190, 70, 16);

        jLabel5.setText("TECHO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(800, 190, 60, 16);

        jLabel6.setText("SUELO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(920, 190, 60, 16);

        jLabel7.setText("VENTILACION");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(790, 260, 100, 16);

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar);
        guardar.setBounds(790, 410, 90, 25);

        costoHabitacion.setText("11");
        getContentPane().add(costoHabitacion);
        costoHabitacion.setBounds(820, 360, 14, 16);

        jLabel2.setText("COSTO TOTAL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(790, 320, 100, 20);

        CALCULAR.setText("CALCULAR");
        CALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARActionPerformed(evt);
            }
        });
        getContentPane().add(CALCULAR);
        CALCULAR.setBounds(790, 590, 100, 25);

        jLabel8.setText("TEMPERATURA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(680, 370, 100, 16);

        jLabel9.setText("odorifero");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(920, 370, 60, 16);

        temperatura.setText("desconocidos");
        getContentPane().add(temperatura);
        temperatura.setBounds(680, 410, 90, 16);

        olor.setText("desconocidos");
        getContentPane().add(olor);
        olor.setBounds(910, 410, 80, 16);

        jLabel10.setText("COSTO DEL EDIFICIO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(770, 690, 190, 16);

        costoEdificio.setText("198");
        getContentPane().add(costoEdificio);
        costoEdificio.setBounds(800, 720, 21, 16);

        jLabel12.setText("MILLONES");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(850, 720, 70, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EDIFICIO MOREDO.png"))); // NOI18N
        jLabel1.setText("HABIYT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -30, 1030, 930);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edi305ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi305ActionPerformed
        numeroHabitacion.setText("305");
        
        pared.setSelectedItem(habitacion305.getParedes());
        techo.setSelectedItem(habitacion305.getTecho());
        suelo.setSelectedItem(habitacion305.getSuelo());
        ventilacion.setSelectedItem(habitacion305.getVentilacion());
        costoHabitacion.setText(habitacion305.getCostoTotal()+"");
        temperatura.setText(habitacion305.getTemperatura());
        olor.setText(habitacion305.getOlor());
    }//GEN-LAST:event_edi305ActionPerformed

    private void edi304ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi304ActionPerformed
        numeroHabitacion.setText("304");
        
        pared.setSelectedItem(habitacion304.getParedes());
        techo.setSelectedItem(habitacion304.getTecho());
        suelo.setSelectedItem(habitacion304.getSuelo());
        ventilacion.setSelectedItem(habitacion304.getVentilacion());
        costoHabitacion.setText(habitacion304.getCostoTotal()+"");
        temperatura.setText(habitacion304.getTemperatura());
        olor.setText(habitacion304.getOlor());
    }//GEN-LAST:event_edi304ActionPerformed

    private void edi301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi301ActionPerformed
        numeroHabitacion.setText("301");
        
        pared.setSelectedItem(habitacion301.getParedes());
        techo.setSelectedItem(habitacion301.getTecho());
        suelo.setSelectedItem(habitacion301.getSuelo());
        ventilacion.setSelectedItem(habitacion301.getVentilacion());
        costoHabitacion.setText(habitacion301.getCostoTotal()+"");
        temperatura.setText(habitacion301.getTemperatura());
        olor.setText(habitacion301.getOlor());
    }//GEN-LAST:event_edi301ActionPerformed

    private void edi303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi303ActionPerformed
        numeroHabitacion.setText("303");
        
        pared.setSelectedItem(habitacion303.getParedes());
        techo.setSelectedItem(habitacion303.getTecho());
        suelo.setSelectedItem(habitacion303.getSuelo());
        ventilacion.setSelectedItem(habitacion303.getVentilacion());
        costoHabitacion.setText(habitacion303.getCostoTotal()+"");
        temperatura.setText(habitacion303.getTemperatura());
        olor.setText(habitacion303.getOlor());
    }//GEN-LAST:event_edi303ActionPerformed

    private void edi302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi302ActionPerformed
        numeroHabitacion.setText("302");
        
        pared.setSelectedItem(habitacion302.getParedes());
        techo.setSelectedItem(habitacion302.getTecho());
        suelo.setSelectedItem(habitacion302.getSuelo());
        ventilacion.setSelectedItem(habitacion302.getVentilacion());
        costoHabitacion.setText(habitacion302.getCostoTotal()+"");
        temperatura.setText(habitacion302.getTemperatura());
        olor.setText(habitacion302.getOlor());
    }//GEN-LAST:event_edi302ActionPerformed

    private void edi306ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi306ActionPerformed
        numeroHabitacion.setText("306");
        
        pared.setSelectedItem(habitacion306.getParedes());
        techo.setSelectedItem(habitacion306.getTecho());
        suelo.setSelectedItem(habitacion306.getSuelo());
        ventilacion.setSelectedItem(habitacion306.getVentilacion());
        costoHabitacion.setText(habitacion306.getCostoTotal()+"");
        temperatura.setText(habitacion306.getTemperatura());
        olor.setText(habitacion306.getOlor());
    }//GEN-LAST:event_edi306ActionPerformed

    private void edi205ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi205ActionPerformed
        numeroHabitacion.setText("205");
        
        pared.setSelectedItem(habitacion205.getParedes());
        techo.setSelectedItem(habitacion205.getTecho());
        suelo.setSelectedItem(habitacion205.getSuelo());
        ventilacion.setSelectedItem(habitacion205.getVentilacion());
        costoHabitacion.setText(habitacion205.getCostoTotal()+"");
        temperatura.setText(habitacion205.getTemperatura());
        olor.setText(habitacion205.getOlor());
    }//GEN-LAST:event_edi205ActionPerformed

    private void edi204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi204ActionPerformed
        numeroHabitacion.setText("204");
        
        pared.setSelectedItem(habitacion204.getParedes());
        techo.setSelectedItem(habitacion204.getTecho());
        suelo.setSelectedItem(habitacion204.getSuelo());
        ventilacion.setSelectedItem(habitacion204.getVentilacion());
        costoHabitacion.setText(habitacion204.getCostoTotal()+"");
        temperatura.setText(habitacion204.getTemperatura());
        olor.setText(habitacion204.getOlor());
    }//GEN-LAST:event_edi204ActionPerformed

    private void edi203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi203ActionPerformed
        numeroHabitacion.setText("203");
        
        pared.setSelectedItem(habitacion203.getParedes());
        techo.setSelectedItem(habitacion203.getTecho());
        suelo.setSelectedItem(habitacion203.getSuelo());
        ventilacion.setSelectedItem(habitacion203.getVentilacion());
        costoHabitacion.setText(habitacion203.getCostoTotal()+"");
        temperatura.setText(habitacion203.getTemperatura());
        olor.setText(habitacion203.getOlor());
    }//GEN-LAST:event_edi203ActionPerformed

    private void edi201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi201ActionPerformed
        numeroHabitacion.setText("201");
        
        pared.setSelectedItem(habitacion201.getParedes());
        techo.setSelectedItem(habitacion201.getTecho());
        suelo.setSelectedItem(habitacion201.getSuelo());
        ventilacion.setSelectedItem(habitacion201.getVentilacion());
        costoHabitacion.setText(habitacion201.getCostoTotal()+"");
        temperatura.setText(habitacion201.getTemperatura());
        olor.setText(habitacion201.getOlor());
    }//GEN-LAST:event_edi201ActionPerformed

    private void edi202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi202ActionPerformed
        numeroHabitacion.setText("202");
        
        pared.setSelectedItem(habitacion202.getParedes());
        techo.setSelectedItem(habitacion202.getTecho());
        suelo.setSelectedItem(habitacion202.getSuelo());
        ventilacion.setSelectedItem(habitacion202.getVentilacion());
        costoHabitacion.setText(habitacion202.getCostoTotal()+"");
        temperatura.setText(habitacion202.getTemperatura());
        olor.setText(habitacion202.getOlor());
    }//GEN-LAST:event_edi202ActionPerformed

    private void edi106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi106ActionPerformed
        numeroHabitacion.setText("106");
        
        pared.setSelectedItem(habitacion106.getParedes());
        techo.setSelectedItem(habitacion106.getTecho());
        suelo.setSelectedItem(habitacion106.getSuelo());
        ventilacion.setSelectedItem(habitacion106.getVentilacion());
        costoHabitacion.setText(habitacion106.getCostoTotal()+"");
        temperatura.setText(habitacion106.getTemperatura());
        olor.setText(habitacion106.getOlor());
    }//GEN-LAST:event_edi106ActionPerformed

    private void edi105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi105ActionPerformed
        numeroHabitacion.setText("105");
        
        pared.setSelectedItem(habitacion105.getParedes());
        techo.setSelectedItem(habitacion105.getTecho());
        suelo.setSelectedItem(habitacion105.getSuelo());
        ventilacion.setSelectedItem(habitacion105.getVentilacion());
        costoHabitacion.setText(habitacion105.getCostoTotal()+"");
        temperatura.setText(habitacion105.getTemperatura());
        olor.setText(habitacion105.getOlor());
    }//GEN-LAST:event_edi105ActionPerformed

    private void edi104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi104ActionPerformed
        numeroHabitacion.setText("104");
        
        pared.setSelectedItem(habitacion104.getParedes());
        techo.setSelectedItem(habitacion104.getTecho());
        suelo.setSelectedItem(habitacion104.getSuelo());
        ventilacion.setSelectedItem(habitacion104.getVentilacion());
        costoHabitacion.setText(habitacion104.getCostoTotal()+"");
        temperatura.setText(habitacion104.getTemperatura());
        olor.setText(habitacion104.getOlor());
    }//GEN-LAST:event_edi104ActionPerformed

    private void edi102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi102ActionPerformed
        numeroHabitacion.setText("102");
        
        pared.setSelectedItem(habitacion102.getParedes());
        techo.setSelectedItem(habitacion102.getTecho());
        suelo.setSelectedItem(habitacion102.getSuelo());
        ventilacion.setSelectedItem(habitacion102.getVentilacion());
        costoHabitacion.setText(habitacion102.getCostoTotal()+"");
        temperatura.setText(habitacion102.getTemperatura());
        olor.setText(habitacion102.getOlor());
    }//GEN-LAST:event_edi102ActionPerformed

    private void edi101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi101ActionPerformed
        numeroHabitacion.setText("101");
        
        pared.setSelectedItem(habitacion101.getParedes());
        techo.setSelectedItem(habitacion101.getTecho());
        suelo.setSelectedItem(habitacion101.getSuelo());
        ventilacion.setSelectedItem(habitacion101.getVentilacion());
        costoHabitacion.setText(habitacion101.getCostoTotal()+"");
        temperatura.setText(habitacion101.getTemperatura());
        olor.setText(habitacion101.getOlor());
    }//GEN-LAST:event_edi101ActionPerformed

    private void edi206ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi206ActionPerformed
        numeroHabitacion.setText("206");
        
        pared.setSelectedItem(habitacion206.getParedes());
        techo.setSelectedItem(habitacion206.getTecho());
        suelo.setSelectedItem(habitacion206.getSuelo());
        ventilacion.setSelectedItem(habitacion206.getVentilacion());
        costoHabitacion.setText(habitacion206.getCostoTotal()+"");
        temperatura.setText(habitacion206.getTemperatura());
        olor.setText(habitacion206.getOlor());
    }//GEN-LAST:event_edi206ActionPerformed

    private void edi103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edi103ActionPerformed
        numeroHabitacion.setText("103");
        
        pared.setSelectedItem(habitacion103.getParedes());
        techo.setSelectedItem(habitacion103.getTecho());
        suelo.setSelectedItem(habitacion103.getSuelo());
        ventilacion.setSelectedItem(habitacion103.getVentilacion());
        costoHabitacion.setText(habitacion103.getCostoTotal()+"");
        temperatura.setText(habitacion103.getTemperatura());
        olor.setText(habitacion103.getOlor());
    }//GEN-LAST:event_edi103ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        String numerohabitacionactual = numeroHabitacion.getText();
        int costoPared=0;
        int costoTecho=0;
        int costoSuelo=0;
        int costoVentilacion=0;
        
        if(pared.getSelectedItem().toString()=="carton"){
            costoPared=5;
        }else if(pared.getSelectedItem().toString()=="cemento"){
            costoPared=10;
        }else if(pared.getSelectedItem().toString()=="sintetico"){
            costoPared=15;
        }
        
        if(techo.getSelectedItem().toString()=="pvc"){
            costoTecho=2;
        }else if(techo.getSelectedItem().toString()=="cemento"){
            costoTecho=5;
        }else if(techo.getSelectedItem().toString()=="sintetico"){
            costoTecho=10;
        }
        
        if(suelo.getSelectedItem().toString()=="pvc"){
            costoSuelo=3;
        }else if(suelo.getSelectedItem().toString()=="cemento"){
            costoSuelo=7;
        }else if(suelo.getSelectedItem().toString()=="sintetico"){
            costoSuelo=14;
        }
        
        if(ventilacion.getSelectedItem().toString()=="regillas"){
            costoVentilacion=1;
        }else if(ventilacion.getSelectedItem().toString()=="ducto"){
            costoVentilacion=2;
        }else if(ventilacion.getSelectedItem().toString()=="aireAcondicionado"){
            costoVentilacion=3;
        }
        
        if(numerohabitacionactual == "101"){
            habitacion101.setParedes(pared.getSelectedItem().toString());
            habitacion101.setSuelo(suelo.getSelectedItem().toString());
            habitacion101.setTecho(techo.getSelectedItem().toString());
            habitacion101.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion101.setCostoParedes(costoPared);
            habitacion101.setCostoSuelo(costoSuelo);
            habitacion101.setCostoTecho(costoTecho);
            habitacion101.setCostoVentilacion(costoVentilacion);
            habitacion101.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion101.getCostoTotal());
            
        }else if(numerohabitacionactual == "102"){
            habitacion102.setParedes(pared.getSelectedItem().toString());
            habitacion102.setSuelo(suelo.getSelectedItem().toString());
            habitacion102.setTecho(techo.getSelectedItem().toString());
            habitacion102.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion102.setCostoParedes(costoPared);
            habitacion102.setCostoSuelo(costoSuelo);
            habitacion102.setCostoTecho(costoTecho);
            habitacion102.setCostoVentilacion(costoVentilacion);
            habitacion102.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion102.getCostoTotal());
        }else if(numerohabitacionactual == "103"){
            habitacion103.setParedes(pared.getSelectedItem().toString());
            habitacion103.setSuelo(suelo.getSelectedItem().toString());
            habitacion103.setTecho(techo.getSelectedItem().toString());
            habitacion103.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion103.setCostoParedes(costoPared);
            habitacion103.setCostoSuelo(costoSuelo);
            habitacion103.setCostoTecho(costoTecho);
            habitacion103.setCostoVentilacion(costoVentilacion);
            habitacion103.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion103.getCostoTotal());
        }else if(numerohabitacionactual == "104"){
            habitacion104.setParedes(pared.getSelectedItem().toString());
            habitacion104.setSuelo(suelo.getSelectedItem().toString());
            habitacion104.setTecho(techo.getSelectedItem().toString());
            habitacion104.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion104.setCostoParedes(costoPared);
            habitacion104.setCostoSuelo(costoSuelo);
            habitacion104.setCostoTecho(costoTecho);
            habitacion104.setCostoVentilacion(costoVentilacion);
            habitacion104.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion104.getCostoTotal());
        }else if(numerohabitacionactual == "105"){
            habitacion105.setParedes(pared.getSelectedItem().toString());
            habitacion105.setSuelo(suelo.getSelectedItem().toString());
            habitacion105.setTecho(techo.getSelectedItem().toString());
            habitacion105.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion105.setCostoParedes(costoPared);
            habitacion105.setCostoSuelo(costoSuelo);
            habitacion105.setCostoTecho(costoTecho);
            habitacion105.setCostoVentilacion(costoVentilacion);
            habitacion105.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion105.getCostoTotal());
        }else if(numerohabitacionactual == "106"){
            habitacion106.setParedes(pared.getSelectedItem().toString());
            habitacion106.setSuelo(suelo.getSelectedItem().toString());
            habitacion106.setTecho(techo.getSelectedItem().toString());
            habitacion106.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion106.setCostoParedes(costoPared);
            habitacion106.setCostoSuelo(costoSuelo);
            habitacion106.setCostoTecho(costoTecho);
            habitacion106.setCostoVentilacion(costoVentilacion);
            habitacion106.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion106.getCostoTotal());
        }else if(numerohabitacionactual == "201"){
            habitacion201.setParedes(pared.getSelectedItem().toString());
            habitacion201.setSuelo(suelo.getSelectedItem().toString());
            habitacion201.setTecho(techo.getSelectedItem().toString());
            habitacion201.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion201.setCostoParedes(costoPared);
            habitacion201.setCostoSuelo(costoSuelo);
            habitacion201.setCostoTecho(costoTecho);
            habitacion201.setCostoVentilacion(costoVentilacion);
            habitacion201.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion201.getCostoTotal());
        }else if(numerohabitacionactual == "202"){
            habitacion202.setParedes(pared.getSelectedItem().toString());
            habitacion202.setSuelo(suelo.getSelectedItem().toString());
            habitacion202.setTecho(techo.getSelectedItem().toString());
            habitacion202.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion202.setCostoParedes(costoPared);
            habitacion202.setCostoSuelo(costoSuelo);
            habitacion202.setCostoTecho(costoTecho);
            habitacion202.setCostoVentilacion(costoVentilacion);
            habitacion202.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion202.getCostoTotal());
        }else if(numerohabitacionactual == "203"){
            habitacion203.setParedes(pared.getSelectedItem().toString());
            habitacion203.setSuelo(suelo.getSelectedItem().toString());
            habitacion203.setTecho(techo.getSelectedItem().toString());
            habitacion203.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion203.setCostoParedes(costoPared);
            habitacion203.setCostoSuelo(costoSuelo);
            habitacion203.setCostoTecho(costoTecho);
            habitacion203.setCostoVentilacion(costoVentilacion);
            habitacion203.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion203.getCostoTotal());
        }else if(numerohabitacionactual == "204"){
            habitacion204.setParedes(pared.getSelectedItem().toString());
            habitacion204.setSuelo(suelo.getSelectedItem().toString());
            habitacion204.setTecho(techo.getSelectedItem().toString());
            habitacion204.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion204.setCostoParedes(costoPared);
            habitacion204.setCostoSuelo(costoSuelo);
            habitacion204.setCostoTecho(costoTecho);
            habitacion204.setCostoVentilacion(costoVentilacion);
            habitacion204.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion204.getCostoTotal());
        }else if(numerohabitacionactual == "205"){
            habitacion205.setParedes(pared.getSelectedItem().toString());
            habitacion205.setSuelo(suelo.getSelectedItem().toString());
            habitacion205.setTecho(techo.getSelectedItem().toString());
            habitacion205.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion205.setCostoParedes(costoPared);
            habitacion205.setCostoSuelo(costoSuelo);
            habitacion205.setCostoTecho(costoTecho);
            habitacion205.setCostoVentilacion(costoVentilacion);
            habitacion205.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion205.getCostoTotal());
        }else if(numerohabitacionactual == "206"){
            habitacion206.setParedes(pared.getSelectedItem().toString());
            habitacion206.setSuelo(suelo.getSelectedItem().toString());
            habitacion206.setTecho(techo.getSelectedItem().toString());
            habitacion206.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion206.setCostoParedes(costoPared);
            habitacion206.setCostoSuelo(costoSuelo);
            habitacion206.setCostoTecho(costoTecho);
            habitacion206.setCostoVentilacion(costoVentilacion);
            habitacion206.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion206.getCostoTotal());
        }else if(numerohabitacionactual == "301"){
            habitacion301.setParedes(pared.getSelectedItem().toString());
            habitacion301.setSuelo(suelo.getSelectedItem().toString());
            habitacion301.setTecho(techo.getSelectedItem().toString());
            habitacion301.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion301.setCostoParedes(costoPared);
            habitacion301.setCostoSuelo(costoSuelo);
            habitacion301.setCostoTecho(costoTecho);
            habitacion301.setCostoVentilacion(costoVentilacion);
            habitacion301.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion301.getCostoTotal());
        }else if(numerohabitacionactual == "302"){
            habitacion302.setParedes(pared.getSelectedItem().toString());
            habitacion302.setSuelo(suelo.getSelectedItem().toString());
            habitacion302.setTecho(techo.getSelectedItem().toString());
            habitacion302.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion302.setCostoParedes(costoPared);
            habitacion302.setCostoSuelo(costoSuelo);
            habitacion302.setCostoTecho(costoTecho);
            habitacion302.setCostoVentilacion(costoVentilacion);
            habitacion302.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion302.getCostoTotal());
        }else if(numerohabitacionactual == "303"){
            habitacion303.setParedes(pared.getSelectedItem().toString());
            habitacion303.setSuelo(suelo.getSelectedItem().toString());
            habitacion303.setTecho(techo.getSelectedItem().toString());
            habitacion303.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion303.setCostoParedes(costoPared);
            habitacion303.setCostoSuelo(costoSuelo);
            habitacion303.setCostoTecho(costoTecho);
            habitacion303.setCostoVentilacion(costoVentilacion);
            habitacion303.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion303.getCostoTotal());
        }else if(numerohabitacionactual == "304"){
            habitacion304.setParedes(pared.getSelectedItem().toString());
            habitacion304.setSuelo(suelo.getSelectedItem().toString());
            habitacion304.setTecho(techo.getSelectedItem().toString());
            habitacion304.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion304.setCostoParedes(costoPared);
            habitacion304.setCostoSuelo(costoSuelo);
            habitacion304.setCostoTecho(costoTecho);
            habitacion304.setCostoVentilacion(costoVentilacion);
            habitacion304.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion304.getCostoTotal());
        }else if(numerohabitacionactual == "305"){
            habitacion305.setParedes(pared.getSelectedItem().toString());
            habitacion305.setSuelo(suelo.getSelectedItem().toString());
            habitacion305.setTecho(techo.getSelectedItem().toString());
            habitacion305.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion305.setCostoParedes(costoPared);
            habitacion305.setCostoSuelo(costoSuelo);
            habitacion305.setCostoTecho(costoTecho);
            habitacion305.setCostoVentilacion(costoVentilacion);
            habitacion305.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion305.getCostoTotal());
        }else if(numerohabitacionactual == "306"){
            habitacion306.setParedes(pared.getSelectedItem().toString());
            habitacion306.setSuelo(suelo.getSelectedItem().toString());
            habitacion306.setTecho(techo.getSelectedItem().toString());
            habitacion306.setVentilacion(ventilacion.getSelectedItem().toString());
            habitacion306.setCostoParedes(costoPared);
            habitacion306.setCostoSuelo(costoSuelo);
            habitacion306.setCostoTecho(costoTecho);
            habitacion306.setCostoVentilacion(costoVentilacion);
            habitacion306.setCostoTotal(costoPared+costoSuelo+costoTecho+costoVentilacion);
            costoHabitacion.setText(""+habitacion306.getCostoTotal());
        }else{
            JOptionPane.showMessageDialog(null, "ocurrio un error: numero de habitacion desconosida");
        }
        int costoTotalEdificio = (habitacion101.getCostoTotal()+habitacion102.getCostoTotal()+habitacion103.getCostoTotal()+habitacion104.getCostoTotal()+habitacion105.getCostoTotal()+habitacion106.getCostoTotal()+habitacion201.getCostoTotal()+habitacion202.getCostoTotal()+habitacion203.getCostoTotal()+habitacion204.getCostoTotal()+habitacion205.getCostoTotal()+habitacion206.getCostoTotal()+habitacion301.getCostoTotal()+habitacion302.getCostoTotal()+habitacion303.getCostoTotal()+habitacion304.getCostoTotal()+habitacion305.getCostoTotal()+habitacion306.getCostoTotal());
        costoEdificio.setText(costoTotalEdificio+"");
    }//GEN-LAST:event_guardarActionPerformed

    private void CALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARActionPerformed
        algoritmo calcular = new algoritmo(habitacion101, habitacion102, habitacion103, habitacion104, habitacion105, habitacion106, habitacion201, habitacion202, habitacion203, habitacion204, habitacion205, habitacion206, habitacion301, habitacion302, habitacion303, habitacion304, habitacion305, habitacion306);
        habitabilidad = calcular.calcularHabitabilidad();
        
        edi101.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[0][2]+".PNG"));
        habitacion101.setTemperatura(habitabilidad[0][0]);
        habitacion101.setOlor(habitabilidad[0][1]);
        
        edi102.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[1][2]+".PNG"));
        habitacion102.setTemperatura(habitabilidad[1][0]);
        habitacion102.setOlor(habitabilidad[1][1]);
        
        edi103.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[2][2]+".PNG"));
        habitacion103.setTemperatura(habitabilidad[2][0]);
        habitacion103.setOlor(habitabilidad[2][1]);
        
        edi104.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[3][2]+".PNG"));
        habitacion104.setTemperatura(habitabilidad[3][0]);
        habitacion104.setOlor(habitabilidad[3][1]);
        
        edi105.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[4][2]+".PNG"));
        habitacion105.setTemperatura(habitabilidad[4][0]);
        habitacion105.setOlor(habitabilidad[4][1]);
        
        edi106.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[5][2]+".PNG"));
        habitacion106.setTemperatura(habitabilidad[5][0]);
        habitacion106.setOlor(habitabilidad[5][1]);
        
        edi201.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[6][2]+".PNG"));
        habitacion201.setTemperatura(habitabilidad[6][0]);
        habitacion201.setOlor(habitabilidad[6][1]);
        
        edi202.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[7][2]+".PNG"));
        habitacion202.setTemperatura(habitabilidad[7][0]);
        habitacion202.setOlor(habitabilidad[7][1]);
        
        edi203.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[8][2]+".PNG"));
        habitacion203.setTemperatura(habitabilidad[8][0]);
        habitacion203.setOlor(habitabilidad[8][1]);
        
        edi204.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[9][2]+".PNG"));
        habitacion204.setTemperatura(habitabilidad[9][0]);
        habitacion204.setOlor(habitabilidad[9][1]);
        
        edi205.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[10][2]+".PNG"));
        habitacion205.setTemperatura(habitabilidad[10][0]);
        habitacion205.setOlor(habitabilidad[10][1]);
        
        edi206.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[11][2]+".PNG"));
        habitacion206.setTemperatura(habitabilidad[11][0]);
        habitacion206.setOlor(habitabilidad[1][1]);
        
        edi301.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[12][2]+".PNG"));
        habitacion301.setTemperatura(habitabilidad[12][0]);
        habitacion301.setOlor(habitabilidad[12][1]);
        
        edi302.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[13][2]+".PNG"));
        habitacion302.setTemperatura(habitabilidad[13][0]);
        habitacion302.setOlor(habitabilidad[13][1]);
        
        edi303.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[14][2]+".PNG"));
        habitacion303.setTemperatura(habitabilidad[14][0]);
        habitacion303.setOlor(habitabilidad[14][1]);
        
        edi304.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[15][2]+".PNG"));
        habitacion304.setTemperatura(habitabilidad[15][0]);
        habitacion304.setOlor(habitabilidad[15][1]);
        
        edi305.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[16][2]+".PNG"));
        habitacion305.setTemperatura(habitabilidad[16][0]);
        habitacion305.setOlor(habitabilidad[16][1]);
        
        edi306.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Documents\\NetBeansProjects\\sexto semestrr\\Habitabbilidad\\src\\imagenes\\"+habitabilidad[17][2]+".PNG"));
        habitacion306.setTemperatura(habitabilidad[17][0]);
        habitacion306.setOlor(habitabilidad[17][1]);
    }//GEN-LAST:event_CALCULARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDIFICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDIFICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDIFICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDIFICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDIFICIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CALCULAR;
    private javax.swing.JLabel costoEdificio;
    private javax.swing.JLabel costoHabitacion;
    private javax.swing.JButton edi101;
    private javax.swing.JButton edi102;
    private javax.swing.JButton edi103;
    private javax.swing.JButton edi104;
    private javax.swing.JButton edi105;
    private javax.swing.JButton edi106;
    private javax.swing.JButton edi201;
    private javax.swing.JButton edi202;
    private javax.swing.JButton edi203;
    private javax.swing.JButton edi204;
    private javax.swing.JButton edi205;
    private javax.swing.JButton edi206;
    private javax.swing.JButton edi301;
    private javax.swing.JButton edi302;
    private javax.swing.JButton edi303;
    private javax.swing.JButton edi304;
    private javax.swing.JButton edi305;
    private javax.swing.JButton edi306;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel numeroHabitacion;
    private javax.swing.JLabel olor;
    private javax.swing.JComboBox<String> pared;
    private javax.swing.JComboBox<String> suelo;
    private javax.swing.JComboBox<String> techo;
    private javax.swing.JLabel temperatura;
    private javax.swing.JComboBox<String> ventilacion;
    // End of variables declaration//GEN-END:variables
}
